### ISSUE TITLE
Create Database Release (Worker Friendly) does not work with vanilla NuGet packages

### ISSUE THREAD

**Issue by davidkeaveny** [OctopusDeploy/Library#1259]
I am attempting to integrate my CI/CD pipeline with the RedGate database deployment tools. I am using Atlassian's BitBucket Pipelines to create deployment packages, and Octopus Deploy (Cloud) to do the actual deployment.

I have set up my database with RedGate's SQL Source Control, and then use octopack to convert the database scripts folder into a NuGet package; however, when I then push that NuGet package to the Octopus internal feed, and attempt to deploy it using the Create Database Release (Worker Friendly) deployment step, I get an error.

RedGate Support have suggested I ask here, given that the step template is hosted from here.

---

### Step template

The step template that I am having issues with is `Create Database Release (Worker Friendly)`, version 3.

### Step template parameter inputs

The step is configured as shown below:

![image](https://user-images.githubusercontent.com/1229960/163887770-098bfc02-ddd6-4ed9-8edd-bf150e4e4b6d.png)

### Step template related environment information

The configured worker is an AWS EC2 instance running Windows Server 2019.

### Octopus Server version

I am running on Octopus Cloud v2022.2 (Build 387-hotfix.903).

### Expected behavior

The Create Database Release should create the scripts necessary to migrate the target database, based on the target scripts extracted from the NuGet package.

### Actual behavior

After downloading all of its dependencies, the Create Database Release step fails when it tries to find the file `BuildArtifact.json`. I have copied the relevant section from the Octopus logs:

```
New-DatabaseConnection, SQL Change Automation 4.4.22097.29877, Copyright c Red Gate Software Ltd 2014-2021 
VERBOSE: Machine Information: 
OperatingSystem: Microsoft Windows NT 10.0.17763.0 
OsBitVersion: x64 
MachineName: EC2AMAZ-VIE2BNV 
CurrentUser: NT AUTHORITY\SYSTEM 
TempDirectory: C:\Windows\TEMP\ 
HostProcessName: powershell 
ProcessorCount: 2 
TotalPhysicalMemory: 2009 MB 
AvailablePhysicalMemory: 344 MB 
Is64BitProcess: True 
INFORMATION - Use of SQL Change Automation requires licensing in line with the Redgate End User License Agreement. 
See Red-gate.com/EULA for more information. 
VERBOSE: Parameters: 
ServerInstance: *****.********.ap-southeast-2.rds.amazonaws.com 
Database: MyApp
Authentication: null 
Username: admin 
Password: ******** 
TrustServerCertificate: False 
Encrypt: False 
Test-DatabaseConnection, SQL Change Automation 4.4.22097.29877, Copyright c Red Gate Software Ltd 2014-2021 
VERBOSE: Parameters: 
InputObject: database 'STP' on server '*****.********.ap-southeast-2.rds.amazonaws.com' 
VERBOSE: Checking connection details for database 'database 'STP' on server  
'dev-stp.cyeouclergk4.ap-southeast-2.rds.amazonaws.com'' 
Import-DatabaseBuildArtifact, SQL Change Automation 4.4.22097.29877, Copyright c Red Gate Software Ltd 2014-2021 
VERBOSE: Parameters: 
Path: C:\Octopus\Applications\Dev-Deployment\Development\MyApp.Database\0.1.0-beta.617_1 
WARNING: Did not find the metadata file  
C:\Octopus\Applications\Dev-Deployment\Development\MyApp.Database\0.1.0-beta.617_1\BuildArtifact.json. Using  
default values 
InvalidData: The file or folder is not a valid build artifact: 'C:\Octopus\Applications\Dev-Deployment\Development\MyApp.Database\0.1.0-beta.617_1'
```

### Steps to reproduce the problem (for bugs)

The configuration for BitBucket Pipelines, which produces the NuGet package, is as follows:

```
image: mcr.microsoft.com/dotnet/sdk:6.0

pipelines:
  default:
    - step:
        name: Build DB
        script:
          - pipe: octopusdeploy/octopus-cli-run:0.38.0
            variables:
               CLI_COMMAND: 'pack'
               ID: 'MyApp.Database'
               FORMAT: 'NuPkg'
               VERSION: $VERSION
               PROJECT: 'MyApp DB'
               SOURCE_PATH: ./MyApp.Database/Scripts
               OUTPUT_PATH: ./published
          - pipe: octopusdeploy/octopus-cli-run:0.38.0
            variables:
               CLI_COMMAND: 'push'
               PACKAGES: [ './published/MyApp.Database.${VERSION}.nupkg' ]
               OCTOPUS_SPACE: 'MyApp'
               OCTOPUS_SERVER: $OCTOPUS_SERVER
               OCTOPUS_APIKEY: $OCTOPUS_APIKEY
          - pipe: octopusdeploy/octopus-cli-run:0.38.0
            variables:
               CLI_COMMAND: 'build-information'
               PROJECT: 'MyApp DB'
               OCTOPUS_SPACE: 'MyApp'
               OCTOPUS_SERVER: $OCTOPUS_SERVER
               OCTOPUS_APIKEY: $OCTOPUS_APIKEY
               VERSION: $VERSION
               PACKAGE_IDS: [ 'MyApp.Database' ]
```
