### ISSUE TITLE
Cloud Formation step template doesn't support transforms

### ISSUE THREAD

**Issue by boonew2** [OctopusDeploy/Library#695]
I might be able to submit a PR for this, but I'm not 100% sure that https://github.com/OctopusDeploy/Library/blob/master/step-templates/aws-cloudformation-create.json is the actual step template in question. It looks like it could be, but i think the step was provided by Octopus and not listed as a community one and I'm not familiar enough with OctopusDeploy to know if that would live here!

---

### Step template
`Deploy an AWS CloudFormation template`

### Step template parameter inputs
Slimmed down version of CF template:
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  RealParam:
    NoEcho: true
    Type: String

Resources:
  AppFunction:
    Properties:
      Code: ../transpiled/indexbundle.js
      CodeUri: s3://valid/bucket/validKey
      Environment:
        Variables:
          REAL_PARAM:
            Ref: RealParam

      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api

      Handler: indexbundle.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  ConfigLambdaPermission:
    DependsOn:
    - AppFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: AppFunction
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
Transform:
- AWS::Serverless-2016-10-31
```

### Step template version
Not sure how to find this...

### Step template related environment information
N/A

### Octopus Server version
2018.5.6

### Expected behavior
CloudFormation stack would be deployed to specified account/region

### Actual behavior
It errors on deploy:
```
Calamari.Aws.Exceptions.UnknownException: AWS-CLOUDFORMATION-ERROR-0008: An unrecognised exception was thrown while creating a CloudFormation stack. 
June 29th 2018 18:34:12Error
For more information visit https://g.octopushq.com/AwsCloudFormationDeploy#aws-cloudformation-error-0008 ---> Amazon.CloudFormation.AmazonCloudFormationException: CreateStack cannot be used with templates containing Transforms. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request. 
```

### Possible solution
Transforms (SAM) in cloudformation require the stacks to be created/updated via changesets instead of the CreateStack operation directly. Instead of calling `New-CFNStack` call `New-CFNChangeSet` with the same params (plus `-ChangeSetName` and `-Description`) and after the changeset is fully created `Start-CFNChangeSet` can kick it off.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html

### Steps to reproduce the problem (for bugs)

The above provided CF template with valid account creds should repro the error. If not providing a parameters json file then default values may need to be added.
